planetarium/mimir

- NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
- NineChroniclesUtilBackend/Arena/AvatarStatesForArena.cs
- NineChroniclesUtilBackend/Controllers/ArenaController.cs
- NineChroniclesUtilBackend/Models/Arena/ArenaResult.cs
- NineChroniclesUtilBackend/Models/Arena/ArenaSimulateResponse.cs
- NineChroniclesUtilBackend/Program.cs
Simply, I've created an API controller for the arena and bulk simulator.
> [Refactor] Add ArenaController, ArenaBulkSimulator

- .vscode/launch.json
- .vscode/tasks.json
- NineChroniclesUtilBackend/Controllers/AgentController.cs
- NineChroniclesUtilBackend/Models/Agent/Avatar.cs
- NineChroniclesUtilBackend/Models/Agent/AvatarsResponse.cs
Add agent controller and implement avatars api (and vscode debug setting files)
> [Feature] AgentController

- NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
> Adjust simulation count 10 -> 700

- NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
- NineChroniclesUtilBackend/Options/HeadlessStateServiceOption.cs
- NineChroniclesUtilBackend/Program.cs
I've implemented JWT authorization to secure headless and other nodes.
> [PDX-359] Implement jwt authorization

- NineChroniclesUtilBackend/.graphqlrc.json
- NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
- NineChroniclesUtilBackend/Queries.graphql
- NineChroniclesUtilBackend/Services/HeadlessStateService.cs
- NineChroniclesUtilBackend/schema.graphql
- update libplanet
- update headless gql (accountAddress)
> Bump libplanet4

- NineChroniclesUtilBackend/Program.cs
> Add health check endpoint

- .github/workflows/docker.yaml
> Store dockerizing

- Mimir/Controllers/TableSheetsController.cs
- Mimir/Mimir.csproj
- Mimir/Program.cs
- Mimir/Repositories/TableSheetsRepository.cs
Close https://github.com/planetarium/mimir/issues/36
> Add table sheets apis

- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Models/State/TableSheetData.cs
- Mimir.Worker/Scrapper/TableSheetScrapper.cs
- Mimir.Worker/Services/MongoDbStore.cs
- Mimir/Controllers/TableSheetsController.cs
- Mimir/Enums/SheetFormat.cs
- Mimir/Mimir.csproj
- Mimir/Repositories/BaseRepositories.cs
- Mimir/Repositories/TableSheetsRepository.cs
- Mimir/Services/MongoDBCollectionService.cs
Implement CSV response in the Table Sheets API for the 9C-Board
> Add table sheet csv store & handle api csv response

- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Scrapper/StateGetter.cs
- Mimir/Arena/ArenaBulkSimulator.cs
- Mimir/Arena/AvatarStatesForArena.cs
- Mimir/Controllers/AgentController.cs
- Mimir/Controllers/ArenaController.cs
- Mimir/Mimir.csproj
- Mimir/Models/Agent/Avatar.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Repositories/CpRepository.cs
- Mimir/Util/StateGetter.cs
It resolves #54 
- Bump Lib9c to latest
- Correct worker's logic to collect actionPoint (avatar)
- Response `actionPoint` field in `<agentAddr>/avatars`
> Response avatar's actionPoint too

- Mimir.Worker/Scrapper/StateGetter.cs
- Mimir/Controllers/AgentController.cs
- Mimir/Models/Agent/Avatar.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Util/StateGetter.cs
> feat(api): include `dailyRewardReceivedIndex` in the `Models.Agent.Avatar` model

- Mimir.Worker/Models/SyncContext.cs
- Mimir.Worker/Services/MongoDbStore.cs
> fix(worker): update `LatestBlockIndex` if it doesn't exist

- Mimir.Worker/Initializer.cs
- Mimir.Worker/Queries.graphql
- Mimir.Worker/Scrapper/ArenaScrapper.cs
- Mimir.Worker/Scrapper/StateGetter.cs
- Mimir.Worker/Scrapper/TableSheetScrapper.cs
- Mimir.Worker/Services/HeadlessStateService.cs
- Mimir.Worker/Services/IStateService.cs
- Mimir.Worker/Services/StateServiceExtensions.cs
- Mimir.Worker/schema.graphql
- Mimir/Queries.graphql
- Mimir/Services/HeadlessStateService.cs
- Mimir/Services/IStateService.cs
- Mimir/Util/StateGetter.cs
- Mimir/schema.graphql
It resolves #60 
It depends on https://github.com/planetarium/NineChronicles.Headless/pull/2477
> fix(worker): fetch states with specific block index

- Mimir.Worker/Initializer.cs
- Mimir.Worker/Queries.graphql
- Mimir.Worker/Scrapper/ArenaScrapper.cs
- Mimir.Worker/Scrapper/StateGetter.cs
- Mimir.Worker/Scrapper/TableSheetScrapper.cs
- Mimir.Worker/Services/HeadlessStateService.cs
- Mimir.Worker/Services/IStateService.cs
- Mimir.Worker/Services/StateServiceExtensions.cs
- Mimir.Worker/schema.graphql
- Mimir/Queries.graphql
- Mimir/Services/HeadlessStateService.cs
- Mimir/Services/IStateService.cs
- Mimir/Util/StateGetter.cs
- Mimir/schema.graphql
#65 assumes that https://github.com/planetarium/NineChronicles.Headless/pull/2477 has already been applied. However, according to the internal release schedule, this might take more than a week, which could delay the deployment of Mimir. So it reverts the PR and I'll open a new PR which reverts revert commit
> Revert "Merge pull request #65 from moreal/fix-index"

- Mimir/Controllers/ArenaController.cs
- Mimir/Controllers/AvatarController.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Repositories/AvatarRepository.cs
> Handle address input

- Mimir/Controllers/ArenaController.cs
- Mimir/Models/Arena/ArenaSeason.cs
- Mimir/Repositories/TableSheetsRepository.cs
> Implement arena season endpoint

- Mimir.Worker/BlockPoller.cs
- Mimir.Worker/Queries.graphql
Close [#53](https://github.com/planetarium/mimir/issues/53)
> Implement patch table sync in block poller

- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AvatarStateHandler.cs
- Mimir.Worker/Handler/IStateHandler.cs
- Mimir.Worker/Handler/InventoryStateHandler.cs
- Mimir.Worker/Scrapper/DiffScrapper.cs
Related to https://github.com/planetarium/mimir/issues/81
> Add inventory handler

- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/WorldInformationStateHandler.cs
> Add world information handler

- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/QuestListStateHandler.cs
Related to https://github.com/planetarium/mimir/issues/81
> Add quest list state handler

- Mimir.Worker.Tests/Handler/ActionPointStateHandlerTests.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Models/State/ActionPointState.cs
- Mimir.Worker/Scrapper/StateGetter.cs
- This pull request should apply the changes of https://github.com/planetarium/mimir/pull/102.
- Resolve https://github.com/planetarium/mimir/issues/104.
- Introduce `ActionPointState` and register to `CollectionNames`.
- Introduce `ActionPointStateHandler` with unit test and register to `ActionHandlerMappings`.
> feat: store Avatar's action point from `DiffScrapper`

- Mimir.Worker.Tests/Handler/ActionPointStateHandlerTests.cs
- Mimir.Worker.Tests/Handler/AvatarStateHandlerTests.cs
- Mimir.Worker.Tests/Handler/LegacyAccountHandlerTests.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
> Update ap handler and update test cases

- Mimir.Worker.Tests/Handler/ActionPointStateHandlerTests.cs
- Mimir.Worker.Tests/Handler/AllRuneStateStateHandlerTests.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AllRuneStateHandler.cs
- Mimir.Worker/Models/State/ActionPointState.cs
- Mimir.Worker/Models/State/AllRuneState.cs
- Resolve https://github.com/planetarium/mimir/issues/109
- Introduce `AllRuneState` with handler
> feat: implement `AllRuneState` with handler

- Mimir.Worker.Tests/Handler/AgentStateHandlerTests.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AgentStateHandler.cs
- Mimir.Worker/Models/State/AgentState.cs
> feat: store `AgentState`

- Mimir.Worker/Extensions/StringExtensions.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
- Mimir.Worker/Handler/AgentStateHandler.cs
- Mimir.Worker/Handler/AllRuneStateHandler.cs
- Mimir.Worker/Handler/AvatarStateHandler.cs
- Mimir.Worker/Handler/CollectionStateHandler.cs
- Mimir.Worker/Handler/IStateHandler.cs
- Mimir.Worker/Handler/InventoryStateHandler.cs
- Mimir.Worker/Handler/LegacyAccountHandler.cs
- Mimir.Worker/Handler/QuestListStateHandler.cs
- Mimir.Worker/Handler/WorldInformationStateHandler.cs
- Mimir.Worker/Scrapper/DiffScrapper.cs
- Mimir.Worker/Services/DiffMongoDbService.cs
The Avatar state is the main parent state related to `action points`, `inventory`, etc. We need to link those collections.
> Implement link to avatar after storing

- Mimir/Repositories/AvatarRepository.cs
- Fix collection name to "avatar".
- Fix BsonDocument keys.
> fix: bugs of `AvatarRepository`

- Mimir.Worker.Tests/Handler/ActionPointStateHandlerTests.cs
- Mimir.Worker.Tests/Handler/DailyRewardStateHandlerTests.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/DailyRewardStateHandler.cs
- Mimir.Worker/Models/State/DailyRewardState.cs
- Mimir/GraphQL/Resolvers/DailyRewardReceivedBlockIndexResolver.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/Program.cs
- Mimir/Repositories/DailyRewardRepository.cs
- Mimir/Repositories/InventoryRespository.cs
- Resolve #130.
- Handle daily reward state.
- Introduce `DailyRewardRepository`.
- Make "dailyRewardReceivedBlockIndex" query.
```graphql
query
{
avatar(planetName: $planetName, address: $avatarAddress)
{
dailyRewardReceivedBlockIndex
}
}
```
```json
{
"data": {
"avatar": {
"dailyRewardReceivedBlockIndex": 999
}
}
}
```
> feat: make "dailyRewardReceivedBlockIndex" query

- Mimir/GraphQL/Resolvers/ActionPointResolver.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/Program.cs
- Mimir/Repositories/ActionPointRepository.cs
- Resolve #136.
- Introduce `ActionPointRepository`.
- Fix action point resolver.
> fix: avatar's action point query resolver

- Mimir/Exceptions/DocumentNotFoundInMongoCollectionException.cs
- Mimir/Exceptions/IDefaultMessageException.cs
- Mimir/Exceptions/KeyNotFoundInBsonDocumentException.cs
- Mimir/Exceptions/UnexpectedTypeOfBsonValueException.cs
- Mimir/GraphQL/ErrorFilter.cs
- Mimir/GraphQL/Resolvers/AgentResolver.cs
- Mimir/GraphQL/Resolvers/AvatarResolver.cs
- Mimir/GraphQL/Resolvers/InventoryResolver.cs
- Mimir/GraphQL/Types/AgentType.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/GraphQL/Types/InventoryType.cs
- Mimir/GraphQL/Types/QueryType.cs
- Mimir/Program.cs
- Mimir/Repositories/ActionPointRepository.cs
- Mimir/Repositories/AgentRepository.cs
- Mimir/Repositories/AllRuneRepository.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Repositories/AvatarRepository.cs
- Mimir/Repositories/CollectionRepository.cs
- Mimir/Repositories/CpRepository.cs
- Mimir/Repositories/DailyRewardRepository.cs
- Mimir/Repositories/InventoryRespository.cs
- Mimir/Repositories/MetadataRepository.cs
- Mimir/Repositories/TableSheetsRepository.cs
- Resolve #129.
- Introduce exceptions: `IDefaultMessageException`, `DocumentNotFoundInMongoCollectionException`, `KeyNotFoundInBsonDocumentException`, `UnexpectedTypeOfBsonValueException`.
- Introduce `ErrorFilter`: handle exceptions above.
- Throw exceptions from each `XyxRepository`s.
- Enable `IncludeExceptionDetails` option.
- Fix some query types.
- Add "inventory" query to root query.
```graphql
query
{
agent(planetName: ODIN, address: "0F5622cB9Fc27670C8fe93513416f6fB8bEdAC63")
{
address
version
}
}
```
```json
{
"errors": [
{
"message": "Document not found in MongoDB collection",
"locations": [
{
"line": 8,
"column": 5
}
],
"path": [
"agent",
"version"
],
"extensions": {
"message": "Document not found in 'agent' collection with filter: 'Address' equals to …
```
> feat: send error messages from GraphQL queries

- .devcontainer/devcontainer.json
- .devcontainer/scripts/postCreateCommand.sh
- .github/dependabot.yml
- .vscode/extensions.json
- Mimir/Properties/launchSettings.json
- Setup devcontainer to be able to work with devcontainer, codespaces.
- Open `/graphql` instead of `/swagger` because GraphQL is mimir's main API.
> Setup devcontainer

- Mimir.Worker/Handler/BaseActionHandler.cs
- Mimir.Worker/Handler/BattleArenaHandler.cs
- Mimir.Worker/Handler/PatchTableHandler.cs
- Mimir.Worker/Handler/ProductsHandler.cs
- Mimir.Worker/Models/State/StateData.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Mimir.Worker/Services/MongoDbService.cs
In addition to the `GameAction` type containing a "type_id" or "values" key, which we were already handling, we now also handle the `ActionBase` type.
> refactor: `BlockPoller` and `BaseActionHandler`

- Mimir.Worker/CollectionUpdaters/ItemSlotCollectionUpdater.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/BaseActionHandler.cs
- Mimir.Worker/Handler/BattleArenaHandler.cs
- Mimir.Worker/Handler/EventDungeonBattleHandler.cs
- Mimir.Worker/Handler/HackAndSlashHandler.cs
- Mimir.Worker/Handler/HackAndSlashSweepHandler.cs
- Mimir.Worker/Handler/JoinArenaHandler.cs
- Mimir.Worker/Handler/RaidHandler.cs
- Mimir.Worker/Models/State/ItemSlotState.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Resolve #150 
- Introduce `ItemSlotState`
- Register collection name "item_slot"
- Add block index param to `BaseActionHandler.HandleAction`
- Introduce `ItemSlotCollectionUpdater`
- Update item slot collection in `BattleArenaHandler`
- Introduce `EventDungeonBattleHandler` for update item slot collection
- Introduce `HackAndSlashHandler` for update item slot collection
- Introduce `HackAndSlashSweepHandler` for update item slot collection
- Introduce `JoinArenaHandler` for update item slot collection
- Introduce `RaidHandler` for update item slot collection
> feat: store `ItemSlotState`

- Mimir.Worker/CollectionUpdaters/RuneSlotCollectionUpdater.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/RuneSlotStateHandler.cs
- Mimir.Worker/Models/State/RuneSlotState.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Resolve #165 
- Introduce `RuneSlotState`
- Register `rune_slot` collection name
- Introduce `RuneSlotCollectionUpdater`
- Introduce `RuneSlotStateHandler`
- Register `RuneSlotStateHandler` to `BlockPoller`
> feat: store `RuneSlotState`

- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/ProductsHandler.cs
- Mimir.Worker/Handler/RaidActionHandler.cs
- Mimir.Worker/Initializer/MarketInitializer.cs
- Mimir.Worker/Models/State/ProductsState.cs
- Mimir.Worker/Models/State/RaiderState.cs
- Mimir.Worker/Models/State/WorldBossKillRewardRecordState.cs
- Mimir.Worker/Models/State/WorldBossState.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Mimir.Worker/Services/MongoDbService.cs
- Mimir.Worker/Util/StateGetter.cs
Close [#160](https://github.com/planetarium/mimir/issues/160)
> Feat: Implement world boss handler

- Mimir.Worker/CollectionUpdaters/StakeCollectionUpdater.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/BaseActionHandler.cs
- Mimir.Worker/Handler/BattleArenaHandler.cs
- Mimir.Worker/Handler/ClaimStakeRewardHandler.cs
- Mimir.Worker/Handler/EventDungeonBattleHandler.cs
- Mimir.Worker/Handler/HackAndSlashHandler.cs
- Mimir.Worker/Handler/HackAndSlashSweepHandler.cs
- Mimir.Worker/Handler/JoinArenaHandler.cs
- Mimir.Worker/Handler/RaidHandler.cs
- Mimir.Worker/Handler/RuneSlotStateHandler.cs
- Mimir.Worker/Handler/StakeHandler.cs
- Mimir.Worker/Models/State/StakeState.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Mimir.Worker/Queries.graphql
- Resolve #151 
- Introduce `StakeState`
- Register `stake` collection name
- Add `signer` field to `ncTransaction` query
- Add `signer` param to `BaseActionHandler.TryHandleAction`
- Introduce `StakeCollectionUpdater`
- Introduce `StakeHandler`
- Introduce `ClaimStakeRewardHandler`
> feat: store `StakeStateV2`

- Mimir.Models/Abstractions/IRuneSlot.cs
- Mimir.Models/Abstractions/IRuneSlots.cs
- Mimir.Models/Abstractions/IStateModel.cs
- Mimir.Models/Mimir.Models.csproj
- Mimir.Models/RuneSlot.cs
- Mimir.Models/RuneSlots.cs
- Mimir.Models/StateModel.cs
- Mimir.Worker/CollectionUpdaters/ItemSlotCollectionUpdater.cs
- Mimir.Worker/CollectionUpdaters/RuneSlotCollectionUpdater.cs
- Mimir.Worker/CollectionUpdaters/StakeCollectionUpdater.cs
- Mimir.Worker/Handler/ProductsHandler.cs
- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Models/State/RuneSlotState.cs
- Mimir.Worker/Services/MongoDbService.cs
- Mimir.Worker/Util/StateGetter.cs
- Mimir.sln
- Mimir/GraphQL/Resolvers/AvatarResolver.cs
- Mimir/GraphQL/Types/RuneSlotType.cs
- Mimir/GraphQL/Types/StakeStateType.cs
- Mimir/Mimir.csproj
- Mimir/Repositories/RuneSlotRepository.cs
- Introduce `Mimir.Models` project with `IStateModel`.
- Introduce `IRuneSlot` and `IRuneSlots`.
- Fix `Mimir.Worker.Models.RuneSlotState`.
- Fix `Mimir.GraphQL.Types.RuneSlotType`.
- Fix `Mimir.GraphQL.Types.StakeStateType`.
> fix: `Mimir.Worker.Models.RuneSlotState`

- Mimir/Controllers/ArenaController.cs
- Mimir/Controllers/MetadataController.cs
- Mimir/Controllers/TableSheetsController.cs
- Mimir/GraphQL/Objects/ArenaObject.cs
- Mimir/GraphQL/Resolvers/ArenaResolver.cs
- Mimir/GraphQL/TypeExtensions/SheetQueryTypeExtension.cs
- Mimir/GraphQL/Types/ArenaSheetRoundDataType.cs
- Mimir/GraphQL/Types/ArenaType.cs
- Mimir/GraphQL/Types/QueryType.cs
- Mimir/Repositories/MetadataRepository.cs
- Mimir/Repositories/TableSheetsRepository.cs
- Refactor `MetadataRepository` and `TableSheetsRepository`.
- Introduce `ArenaSheetRoundDataType` and `ArenaType` with resolver.
- Add `arena` GraphQL query.
> feat: make `arena` GraphQL query

- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/GoldBalanceHandler.cs
- Mimir.Worker/Models/State/GoldBalanceState.cs
> Implement gold balance handler

- Mimir.Worker.Tests/Handler/AdventureBossSeasonInfoHandlerTests.cs
- Mimir.Worker/Handler/ActionPointStateHandler.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AdventureBossSeasonInfoHandler.cs
- Mimir.Worker/Models/State/AdventureBossSeasonInfoState.cs
> feat: Introduce `AdventureBossSeasonInfoHandler`

- Mimir.Worker.Tests/Handler/AdventureBoss/BountyBoardHandlerTests.cs
- Mimir.Worker.Tests/Handler/AdventureBoss/SeasonInfoHandlerTests.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AdventureBoss/BountyBoardHandler.cs
- Mimir.Worker/Handler/AdventureBoss/SeasonInfoHandler.cs
- Mimir.Worker/Models/State/AdventureBoss/BountyBoardState.cs
- Mimir.Worker/Models/State/AdventureBoss/SeasonInfoState.cs
> feat: Introduce `BountyBoardHandler` of `AdventureBoss`

- Mimir.Worker.Tests/Handler/AdventureBoss/BountyBoardHandlerTests.cs
- Mimir.Worker.Tests/Handler/AdventureBoss/ExploreBoardHandlerTests.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AdventureBoss/ExploreBoardHandler.cs
- Mimir.Worker/Models/State/AdventureBoss/ExploreBoardState.cs
> feat: Introduce AdventureBossExploreBoardHandler

- Mimir.Worker.Tests/Handler/AdventureBoss/ExplorerListHandlerTests.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AdventureBoss/ExplorerListHandler.cs
- Mimir.Worker/Models/State/AdventureBoss/ExplorerListState.cs
> feat: Introduce `ExplorerListState` and `ExplorerListHandler`

- Mimir.Worker.Tests/Handler/AdventureBoss/ExploreBoardHandlerTests.cs
- Mimir.Worker/Exceptions/UnexpectedStateException.cs
- Mimir.Worker/Handler/AdventureBoss/ExploreBoardHandler.cs
- Mimir.Worker/Models/State/AdventureBoss/ExplorerState.cs
> feat: apply `ExplorerState` to `ExploreBoardHandler`

- Mimir/GraphQL/Resolvers/AdventureBossResolver.cs
- Mimir/GraphQL/Types/AdventureBossType.cs
- Mimir/Repositories/AdventureBoss/SeasonInfoRepository.cs
> chore: fix typo

- Mimir.Models/Assets/FungibleAssetValue.cs
- Mimir.Models/AttachmentActionResults/AttachmentActionResult.cs
- Mimir.Models/AttachmentActionResults/Buy7BuyerResult.cs
- Mimir.Models/AttachmentActionResults/Buy7SellerResult.cs
- Mimir.Models/AttachmentActionResults/CombinationConsumable5Result.cs
- Mimir.Models/AttachmentActionResults/DailyReward2Result.cs
- Mimir.Models/AttachmentActionResults/ItemEnhancement11Result.cs
- Mimir.Models/AttachmentActionResults/ItemEnhancement12Result.cs
- Mimir.Models/AttachmentActionResults/ItemEnhancement13Result.cs
- Mimir.Models/AttachmentActionResults/ItemEnhancement7Result.cs
- Mimir.Models/AttachmentActionResults/ItemEnhancement9Result.cs
- Mimir.Models/AttachmentActionResults/MonsterCollectionResult.cs
- Mimir.Models/AttachmentActionResults/RapidCombination0Result.cs
- Mimir.Models/AttachmentActionResults/RapidCombination5Result.cs
- Mimir.Models/AttachmentActionResults/SellCancellationResult.cs
- Mimir.Models/Exceptions/UnsupportedArgumentTypeException.cs
- Mimir.Models/Exceptions/UnsupportedArgumentValueException.cs
- Mimir.Models/Factories/AttachmentActionResultFactory.cs
- Mimir.Models/Factories/ItemFactory.cs
- Mimir.Models/Item/Material.cs
- Mimir.Models/Item/ShopItem.cs
- Mimir.Models/Item/TradableMaterial.cs
- Mimir.sln.DotSettings
- Introduce `UnsupportedArgumentTypeException` and `UnsupportedArgumentValueException`.
- Introduce `Mimir.Models.Assets.FungibleAssetValue`.
- Register some words: `bencoded`, `tradable`.
- Introduce `AttachmentActionResult`(s).
- Introduce `AttachmentActionResultFactory`.
- Introduce `ShopItem`.
> Introduce `AttachmentActionResult` models

- Lib9c.Models.Tests/Runes/RuneSlotTest.cs
- Lib9c.Models.Tests/States/AllRuneStateTest.cs
- Lib9c.Models.Tests/States/ItemSlotStateTest.cs
- Lib9c.Models.Tests/States/RuneSlotStateTest.cs
- Lib9c.Models.Tests/States/RuneStateTest.cs
- Lib9c.Models/States/ItemSlotState.cs
- Introduce `ItemSlotState` model.
- Fix `RuneSlotTest`.
- Replace `RuneStateTest` and `AllRuneStateTest`.
- Add `RuneSlotStateTest`.
> Introduce `ItemSlotState` model

- Lib9c.Models.Tests/States/AvatarStateTest.cs
- Lib9c.Models/Factories/ItemFactory.cs
- Lib9c.Models/Items/Grimoire.cs
- Lib9c.Models/States/AvatarState.cs
- Add `Grimoire` model.
- Rename `Avatar` to `AvatarState`.
> add `Grimoire` model

- Lib9c.GraphQL/Types/BencodexIValueType.cs
- Mimir.sln.DotSettings
- Mimir/GraphQL/Types/AgentType.cs
- Mimir/GraphQL/Types/QueryType.cs
- Mimir/Repositories/AvatarRepository.cs
- Fix "avatar" query.
- Disable "adventureBoss" and "stake" GraphQL queries.
- Fix `AvatarRepository`.
- Introduce `BencodexIValueType`.
> bug fix: some GraphQL queries

- Mimir/Repositories/ArenaRepository.cs
> bug fix: "arena" -> "leaderboard" bug temporary

- Mimir/Repositories/TableSheetsRepository.cs
> bug fix: `TableSheetsRepository`

- Mimir/GraphQL/HttpResponseFormatter.cs
- Mimir/Program.cs
> introduce and register `HttpResponseFormatter`

- Mimir/Models/Arena/ArenaRanking.cs
- Mimir/Repositories/ArenaRepository.cs
> fix arena leaderboard rank formula

- Mimir/GraphQL/Queries/Query.cs
- Mimir/GraphQL/TypeExtensions/SheetNamesQueryTypeExtension.cs
- Mimir/GraphQL/TypeExtensions/SheetQueryTypeExtension.cs
- Mimir/Mimir.csproj
> add GraphQL descriptions

- Mimir/GraphQL/Queries/Query.cs
- Mimir/Repositories/ArenaRepository.cs
> fix sorting

- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Lib9c.Models.csproj
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Util/ChainUtil.cs
- Mimir/Mimir.csproj
> bump lib9c

- Mimir.Worker/Mimir.Worker.csproj
> bump `Lib9c.Abstractions`

- Mimir.Worker/ActionHandler/BattleArenaHandler.cs
- Mimir.Worker/Services/HeadlessStateService.cs
- Mimir.Worker/Util/StateGetter.cs
Use the `ChampionshipId` and `Round` contained in the `BattleArena` action.
> bugfix: `ArgumentNullException` of `BattleArenaHandler`

- Mimir/GraphQL/Resolvers/ArenaResolver.cs
- Mimir/GraphQL/Types/ArenaType.cs
- Mimir/Repositories/ArenaRepository.cs
> improve arena logic

- Mimir/GraphQL/TypeExtensions/SheetNamesQueryTypeExtension.cs
- Mimir/Repositories/TableSheetsRepository.cs
> fix "sheetnames" GraphQL query

- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Factories/ProductFactory.cs
- Lib9c.Models/Lib9c.Models.csproj
- Lib9c.Models/Market/ItemProduct.cs
- Lib9c.Models/Market/Product.cs
- Lib9c.Models/States/ProductsState.cs
- Mimir.MongoDB/Bson/ProductDocument.cs
- Mimir.MongoDB/Bson/ProductsDocument.cs
- Mimir.MongoDB/Bson/ProductsStateDocument.cs
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Worker/ActionHandler/ProductsHandler.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Poller/TxPoller.cs
- Mimir.Worker/Services/MongoDbService.cs
- Mimir.Worker/Util/StateGetter.cs
- Mimir/Mimir.csproj
Realted to https://github.com/planetarium/mimir/issues/309
- Bump lib9c
- Uncomment products, product handler
- Fix TradableItem type
> Reactivate products handler

- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
Related to https://github.com/planetarium/mimir/issues/312
> Uncomment balance handler

- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
> Reactivate inventory

- Mimir.Worker/Services/MongoDbService.cs
> Fix not found balance collection name

- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Program.cs
> Uncomment NCG Handler temporarily

- scripts/indexes.json
> Add default address unique index

- Lib9c.Models/Stake/Contract.cs
- Lib9c.Models/States/StakeState.cs
- Mimir.MongoDB/Bson/StakeDocument.cs
- Mimir.MongoDB/CollectionNames.cs
- Mimir.Worker/ActionHandler/StakeHandler.cs
- Mimir.Worker/CollectionUpdaters/StakeCollectionUpdater.cs
- Mimir.Worker/Poller/TxPoller.cs
Related to https://github.com/planetarium/mimir/issues/321
> Reactivate stake handler

- Mimir.Worker/Poller/TxPoller.cs
This pull request has context from https://github.com/planetarium/mimir/pull/330#discussion_r1764565125. If it is necessary, this pull request must be closed.
> Remove unnecessary duplicated collection name

- Mimir.MongoDB/Bson/StakeDocument.cs
- Mimir.Worker/CollectionUpdaters/StakeCollectionUpdater.cs
> Add agent address when storing stake state

- Lib9c.Models/Stake/Contract.cs
- Lib9c.Models/States/StakeState.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- Mimir/Repositories/StakeRepository.cs
Related to https://github.com/planetarium/mimir/issues/321
> Implement stake state gql type

- Mimir.MongoDB/Bson/StakeDocument.cs
- Mimir.Worker/CollectionUpdaters/StakeCollectionUpdater.cs
- Mimir.Worker/Constants/PlanetType.cs
- Mimir/GraphQL/Queries/Query.cs
> fix: handling the `StakeState` can be null.

- Mimir.Worker/Services/MongoDbService.cs
> fix: Json serialization for `SheetDocument`

- Mimir.Worker/Poller/DiffPoller/DiffConsumer.cs
Fixes issue #341 
This is a redo of PR #348 so it can be counted by Hacktoberfest.
> Fix typo (DiffCOunt → DiffCount)

- Mimir.Worker/ActionHandler/RequestPledgeHandler.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- Mimir/Repositories/PledgeRepository.cs
> feat: introduce GraphQL query for pledge

- Mimir.Worker/ActionHandler/ApprovePledgeHandler.cs
> fix address in `ApprovePledgeHandler`

- Mimir.Worker/Configuration.cs
- Mimir.Worker/Mimir.Worker.csproj
- Mimir.Worker/Program.cs
This pull request brought Sentry feature again! For backward-compatibility, it enables only when `Configuration.SentryDsn` is given. Sentry will help us debug.
> Introduce Sentry again

- Mimir/GraphQL/ErrorFilter.cs
- Mimir/Mimir.csproj
- Mimir/Program.cs
- Mimir/appsettings.Development.json
- Mimir/appsettings.json
> Apply Sentry to Mimir

- Mimir.Worker/ActionHandler/RaiderStateHandler.cs
- Mimir.Worker/ActionHandler/WorldBossKillRewardRecordStateHandler.cs
- Mimir.Worker/ActionHandler/WorldBossStateHandler.cs
- Mimir.Worker/Poller/TxPoller.cs
> Split `RaidHandler`

- Mimir.Worker/Poller/TxPoller.cs
> Remove `AllCombinationSlotStateDocument` from `TxPoller._collectionNames`

- Lib9c.Models/WorldInformation/World.cs
- Mimir.MongoDB/Repositories/WorldInformationRepository.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
Related to https://github.com/planetarium/mimir/issues/323
> Implement world information gql

- Mimir.MongoDB/Repositories/CollectionRepository.cs
> bugfix: set `async` and `await` keywords to `CollectionRepository.GetByAddressAsync(address)` method

- Mimir/GraphQL/Queries/Query.cs
Fixes #414
Added GetRunesAsync summary
> docs: get runes async summary

- Mimir.E2ETests/ActionPointTests.cs
- Mimir.E2ETests/MimirGQL/query.graphql
Related to https://github.com/planetarium/mimir/issues/430
> implement ActionPointTests

- Mimir.E2ETests/DailyRewardTests.cs
- Mimir.E2ETests/MimirGQL/query.graphql
- 이 Pull Request는 Issue #432 를 해결합니다.
> DailyReward Test

- Mimir.E2ETests/Mimir.E2ETests.csproj
- 이 Pull Request는 Issue #436를 해결하였습니다.
> Mimir.E2ETests.csproj 수정

- Mimir.E2ETests/AvatarTests.cs
- Mimir.E2ETests/MimirGQL/query.graphql
> feat: Add Avatar Test

- Mimir.E2ETests/HeadlessGQL/schema.graphql
- Mimir.E2ETests/InventoryTests.cs
- Mimir.E2ETests/MimirGQL/query.graphql
- Mimir.E2ETests/MimirGQL/schema.graphql
- Resolve #439 
- Update Headless Schema, Mimir Schema
> Add InventoryTests

- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Lib9c.Models.csproj
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Worker/Client/HeadlessGQLClient.cs
- Mimir.Worker/Mimir.Worker.csproj
- Mimir/Mimir.csproj
- Cache transactions request
- Bump Libplanet version
> Cache transactions request

- Mimir.E2ETests/GraphQLClientFixture.cs
- Mimir.E2ETests/HeadlessGQL/.graphqlrc.json
- Mimir.Worker/ActionHandler/PetStateHandler.cs
- Mimir.Worker/appsettings.json
- Resolve #461
- Fix headless endpoints of `odin`
> fix: exception in `PetStateHandler`

- Mimir.Worker/ActionHandler/PetStateHandler.cs
- Mimir.Worker/Util/StateGetter.cs
> fix: `InvalidCastException` in `PetStateHandler`

- Mimir.E2ETests/AgentTests.cs
- Mimir.E2ETests/MimirGQL/query.graphql
add world_information https://github.com/planetarium/mimir/issues/433 
ID value imported from mirInaccurate annotation processing.
> add world information e2e test #433

- Mimir.E2ETests/AvatarTests.cs
add the remaining field comparisons to tests that compare only one existing field.
> add all field value comparisons to existing tests

- Mimir.sln
> chore: remove `Mimir.E2ETests` project in solution settings

- Mimir.Worker/HostApplicationBuilderExtensions.cs
Related to https://github.com/planetarium/mimir/issues/479
> Disable inventory handler

- Mimir.MongoDB/Models/ProductFilter.cs
- Mimir.MongoDB/Repositories/ProductRepository.cs
- Mimir/GraphQL/Types/ProductFilterInputType.cs
- Mimir/GraphQL/Types/QueryType.cs
- solves #475 
- solves the remaining PR comments from #470
> Issue 475: Address PR review comments

- Mimir.Worker/ActionHandler/BaseActionHandler.cs
- Mimir.Worker/Client/HeadlessGQLClient.cs
- Mimir.Worker/Client/IHeadlessGQLClient.cs
- Mimir.Worker/Handler/BaseDiffHandler.cs
- Mimir.Worker/Services/HeadlessStateService.cs
> hotfix: log more info

- Mimir.Initializer/Initializer/SnapshotInitializer.cs
- Mimir.MongoDB/Bson/ActionPointDocument.cs
- Mimir.MongoDB/Bson/AgentDocument.cs
- Mimir.MongoDB/Bson/AllCombinationSlotStateDocument.cs
- Mimir.MongoDB/Bson/AllRuneDocument.cs
- Mimir.MongoDB/Bson/ArenaDocument.cs
- Mimir.MongoDB/Bson/ArenaParticipantDocument.cs
- Mimir.MongoDB/Bson/AvatarDocument.cs
- Mimir.MongoDB/Bson/BalanceDocument.cs
- Mimir.MongoDB/Bson/CollectionDocument.cs
- Mimir.MongoDB/Bson/DailyRewardDocument.cs
- Mimir.MongoDB/Bson/InventoryDocument.cs
- Mimir.MongoDB/Bson/ItemSlotDocument.cs
- Mimir.MongoDB/Bson/MimirBsonDocument.cs
- Mimir.MongoDB/Bson/MimirBsonDocumentExtensions.cs
- Mimir.MongoDB/Bson/PetStateDocument.cs
- Mimir.MongoDB/Bson/PledgeDocument.cs
- Mimir.MongoDB/Bson/ProductDocument.cs
- Mimir.MongoDB/Bson/ProductsStateDocument.cs
- Mimir.MongoDB/Bson/RaiderStateDocument.cs
- Mimir.MongoDB/Bson/SheetDocument.cs
- Mimir.MongoDB/Bson/StakeDocument.cs
- Mimir.MongoDB/Bson/WorldBossKillRewardRecordDocument.cs
- Mimir.MongoDB/Bson/WorldBossStateDocument.cs
- Mimir.MongoDB/Bson/WorldInformationDocument.cs
- Mimir.Worker/Services/MongoDbService.cs
> Each Arena round will have a unique ID

- Lib9c.GraphQL.Tests/Extensions/CurrencyInputExtensionsTest.cs
- Lib9c.GraphQL.Tests/Lib9c.GraphQL.Tests.csproj
- Mimir.sln
- introduce `Lib9c.GraphQL.Tests` project
- add unit test for `CurrencyInputExtentions`
> Introduce `Lib9c.GraphQL.Tests` project w/ first unit test

- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Lib9c.Models.csproj
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Worker/Mimir.Worker.csproj
- Mimir/Mimir.csproj
> bump: libplanet 5.4.0

- Mimir.MongoDB/Repositories/DailyRewardRepository.cs
- Mimir.Tests/QueryTests/DailyRewardQueryTest.GraphQL_Query_DailyRewardReceivedBlockIndex_Returns_CorrectValue.verified.txt
- Mimir.Tests/QueryTests/DailyRewardQueryTest.cs
- Mimir.Tests/TestServices.cs
- Mimir/GraphQL/Queries/Query.cs
Solve #521 
add DailyRewardTest
> add DailyRewardTest

- Mimir.Worker/Client/HeadlessGQLClient.cs
> change log level for retires to be debug instead of fatal

- Lib9c.Models/Mails/Mail.cs
- Lib9c.Models/Mails/MailBox.cs
- Lib9c.Models/States/AvatarState.cs
- Mimir.MongoDB/Repositories/AvatarRepository.cs
- Mimir.MongoDB/Repositories/IAvatarRepository.cs
- Mimir.Tests/QueryTests/AvatarQueryTest.GraphQL_Query_Avatar_Returns_CorrectValue.verified.txt
- Mimir.Tests/QueryTests/AvatarQueryTest.cs
- Mimir.Tests/TestServices.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
> add snapshot test for avatar query

- Lib9c.GraphQL.Tests/Extensions/CurrencyTickerStringExtensionsTest.cs
> add test for currency ticker string extension method 'ToCurrency()'

- README.md
https://nine-chronicles.dev/modding/guide/avatar-information-dapp-guide 
->
https://nine-chronicles.dev/tutorials/modding/avatar-information-dapp-guide
> Fix broken README external link

- Lib9c.Models/Items/Inventory.cs
- Lib9c.Models/Items/InventoryItem.cs
- Mimir.MongoDB/Repositories/InventoryRepository.cs
- Mimir.Tests/Mimir.Tests.csproj
- Mimir.Tests/QueryTests/InventoryTest.GraphQL_Query_Inventory_Returns_CorrectValue.verified.txt
- Mimir.Tests/QueryTests/InventoryTest.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
Issue: There is issue with the merge in relation to itemId. 
So, Temporary fix is to remove the itemId from the query.
> Add integration test for Inventory Query

- Lib9c.Models/Stake/Contract.cs
- Lib9c.Models/States/StakeState.cs
- Mimir.MongoDB/Repositories/StakeRepository.cs
- Mimir.Tests/QueryTests/StakeTest.GraphQL_Query_Stake_Returns_CorrectValue.verified.txt
- Mimir.Tests/QueryTests/StakeTest.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
solve #552
Add integration Test for Stake Metadata Query
> Add integration Test for Stake Metadata Query #552

- Mimir.MongoDB/Repositories/ProductRepository.cs
- Mimir.MongoDB/Repositories/ProductsRepository.cs
- Mimir/GraphQL/Types/QueryType.cs
resolves #566 
- add Get to IProductRepository
- request IProductRepository from DI in QueryType
> Issue 566: Fix error on querying products

- Directory.Build.props
- Lib9c.GraphQL.Tests/Lib9c.GraphQL.Tests.csproj
lib9c 1.21.0 is not deployed...
> Bump-lib9c-1.20.1-dev-e63950

- Directory.Build.props
- Lib9c.GraphQL.Tests/Lib9c.GraphQL.Tests.csproj
> Bump lib9c 1.21.0

- Mimir.MongoDB/Enums/ProductSortBy.cs
- Mimir.MongoDB/Repositories/ProductRepository.cs
solves #577 
- add new ProductSortBy.CrystalPerPrice
- implement product sorting for CP, Crystal and CrystalPerPrice
>  Add ProductSortBy for CombatPoints, Crystal and CrystalPerPrice

- Lib9c.Models/Block/Action.cs
- Lib9c.Models/Block/Block.cs
- Lib9c.Models/Block/Transaction.cs
- Mimir.MongoDB/Bson/BlockDocument.cs
- Mimir.MongoDB/CollectionNames.cs
- Mimir.MongoDB/Repositories/BlockRepository.cs
- Mimir.Worker/Client/HeadlessGQLClient.cs
- Mimir.Worker/Client/IHeadlessGQLClient.cs
- Mimir.Worker/Client/Models.cs
- Mimir.Worker/Client/Queries.cs
- Mimir.Worker/Constants/PollerType.cs
- Mimir.Worker/Extensions/BlockExtensions.cs
- Mimir.Worker/Handler/Block/BlockHandler.cs
- Mimir.Worker/HostApplicationBuilderExtensions.cs
- Mimir.Worker/Services/MongoDbService.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- docker-compose.yml
Resolve https://github.com/planetarium/mimir/issues/606
> Store blocks

- Lib9c.Models.Tests/Items/EquipmentTest.cs
- Lib9c.Models/Extensions/StateExtensions.cs
- Lib9c.Models/Factories/ItemFactory.cs
- Lib9c.Models/Items/ItemBase.cs
- Lib9c.Models/Items/Material.cs
- ItemFactory.Deserialize 호환성 버그 수정
- 공통속성 메서드들을 나눠서 Dictionary, List 케이스 대응
> Refactor ItemFactory.Deserialize
