planetarium/mimir

- NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
- NineChroniclesUtilBackend/Controllers/ArenaController.cs
- NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
- NineChroniclesUtilBackend/Options/EmptyChronicleOption.cs
- NineChroniclesUtilBackend/Program.cs
- NineChroniclesUtilBackend/Repositories/ArenaRankingRespository.cs
- NineChroniclesUtilBackend/Repositories/CpRepository.cs
- NineChroniclesUtilBackend/Services/HeadlessStateService.cs
- NineChroniclesUtilBackend/Services/IStateService.cs
- NineChroniclesUtilBackend/Util/StateGetter.cs
I've updated lib9c to the latest version and processed the collection data.
During the process, I removed the existing 0c dependency and temporarily modified it to handle it headlessly.
The reason is that there was too much duplication in the code fetching the state, so I aimed to make it more utilitarian and consolidate it.
Since it wouldn't work without addressing the previously unprocessed Account Address, I also carried out work on that in the same branch.
> [PDX-401] Handle collection

- NineChroniclesUtilBackend.Store/BlockPoller.cs
- NineChroniclesUtilBackend.Store/Initializer.cs
- NineChroniclesUtilBackend.Store/Queries.graphql
- NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
- NineChroniclesUtilBackend.Store/Services/MongoDbStore.cs
This pull request does:
- Stop scrapping when cancellation requested.
- Update avatar, arena data by polling.
- Run scrapping every running. (start)
> PDX-396: Update arena, avatar when `battle_arena*` occurred. 

- Mimir/Options/HeadlessStateServiceOption.cs
- Mimir/Program.cs
- Mimir/appsettings.json
Currently, it only receives one GraphQL endpoint, which makes the network parameter irrelevant. I dynamically set the HttpClient via the HttpContextAccessor and fetch it per network. This change requires a bit more configuration in the appsettings.json.
> fix(api): request GraphQL by network name

- Mimir/Controllers/AvatarController.cs
- Mimir/Models/Items/Equipment.cs
- Mimir/Models/Items/Item.cs
- Handle 400 bad request.
- Replace `NonFungibleId` to `Item`
> Improve avatar inventory logic

- Mimir/Controllers/AgentController.cs
- Mimir/Controllers/AvatarController.cs
- Mimir/Models/Agent/Avatar.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Repositories/AvatarRepository.cs
request
```
curl -X 'GET' \
'http://localhost:5195/odin/avatars/0xe56d432da2032f6c851943b76c4a41815baabb54' \
-H 'accept: text/plain'
```
response
```
{
"agentAddress": "0x6132331720A774274d6E51CaeAd375068cC00505",
"avatarAddress": "0xe56d432da2032f6C851943b76C4a41815baaBB54",
"avatarName": "SuhoDaddy",
"level": 299,
"actionPoint": 120,
"dailyRewardReceivedIndex": 10433055
}
```
> feat: introduce "{network}/avatars/{address}"

- Mimir/Controllers/AgentController.cs
- Mimir/Controllers/AvatarController.cs
- Mimir/Controllers/BalanceController.cs
- Mimir/Models/Assets/Balance.cs
- Mimir/Queries.graphql
- Mimir/Services/HeadlessStateService.cs
- Mimir/Services/IStateService.cs
- Mimir/Util/StateGetter.cs
- Mimir/Validators/AddressValidator.cs
- Introduce `Models.Assets.Balance`
- Introduce `Validators.AddressValidator`
- Introduce "{network}/agent/{address}/balances"
- Introduce `BalanceController` with "{network}/balances/{address}/{currency}"
> feat: introduce several balance APIs

- Mimir/GraphQL/Objects/AgentObject.cs
- Mimir/GraphQL/Objects/AvatarObject.cs
- Mimir/GraphQL/Types/AgentType.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/GraphQL/Types/QueryType.cs
- Introduce "agent" query.
- Add "Address" property to "AvatarObject".
```graphql
query (
$planetName: PlanetName! = ODIN,
$agentAddress: Address! = "0xCEB5910a777394a809516D34fEc6f964461413EF") {
agent(planetName: $planetName, address: $agentAddress)
{
avatar(index: 1)
{
name
}
avatars
{
address
name
}
}
}
```
```json
{
"data": {
"agent": {
"avatar": {
"name": "Vall7777"
},
"avatars": [
{
"address": "0xf6BC3f19842AE7d0CD96AA50F7B1bb52735FfE1c",
"name": "VaaV"
},
{
"address": "0x4D5E42553f35c711f4f07757cf73A97a2F69E69c",
"name": "Vall7777"
},
{
"address": "0xb5981087B2eEDD93262e0B09146c2a4aB9AA9c3B",
"name": null
}
]
}
}
```
> feat: introduce "agent" query

- Mimir.Worker/BlockPoller.cs
- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AvatarStateHandler.cs
- Mimir.Worker/Handler/IStateHandler.cs
- Mimir.Worker/Handler/InventoryStateHandler.cs
- Mimir.Worker/Handler/LegacyAccountHandler.cs
- Mimir.Worker/Handler/QuestListStateHandler.cs
- Mimir.Worker/Handler/StateDiffContext.cs
- Mimir.Worker/Handler/WorldInformationStateHandler.cs
- Mimir.Worker/Models/State/ArenaInformationState.cs
- Mimir.Worker/Models/State/ArenaScoreState.cs
- Mimir.Worker/Queries.graphql
- Mimir.Worker/Scrapper/DiffScrapper.cs
- Mimir.Worker/SnapshotInitializer.cs
Close https://github.com/planetarium/mimir/issues/87
The arena handlers are quite messy and not well-optimized 😭.
I need to think about how to make the code more efficient, but for now, it works. 👍 
First, it retrieves all the transactions existing in the block and checks their actions.
If there's a `battle_arena` action, it collects the avatar addresses from the action values.
Then, it pre-generates a large number of derived addresses and matches them accordingly.
> Implement arena info, score state handlers in legacy account handler

- Mimir.Worker/DiffBlockPoller.cs
- Mimir.Worker/Models/State/WorldInfomationState.cs
- Mimir.Worker/Util/StateJsonConverter.cs
Some state classes implemented `GetObjectData` method
```
https://www.newtonsoft.com/json/help/html/SerializationGuide.htm
ISerializable
Types that implement [ISerializable](http://msdn2.microsoft.com/en-us/library/wf4375ks) and are marked with [SerializableAttribute](http://msdn2.microsoft.com/en-us/library/bcfsa90a) are serialized as JSON objects. When serializing, only the values returned from ISerializable.GetObjectData are used; members on the type are ignored. When deserializing, the constructor with a SerializationInfo and StreamingContext is called, passing the JSON object's values.
```
Unfortunately, we don't want to `serialized` value So I added ignore option
> Ignore Serialized values

- .github/workflows/docker.yaml
Looking at the other PRs, I realize that the main branch is deploying Docker images even though it's a branch, so I raise this PR to correct that.
> ci(gh-actions): push docker image on only main branch

- .github/workflows/build.yaml
I've seen situations where I've gone back later and fixed the test project code, because I wasn't checking in the pull_request whether the test project builds and the test passes. So in this PR, we're going to have it checked in every push, every pull_request.
> ci(gh-actions): run dotnet-test in CI

- Mimir/Exceptions/KeyNotFoundInBsonDocumentException.cs
- Mimir/Exceptions/UnexpectedTypeOfBsonValueException.cs
- Mimir/GraphQL/Resolvers/AvatarResolver.cs
- Mimir/GraphQL/Types/AgentType.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/GraphQL/Types/ItemSlotType.cs
- Mimir/Program.cs
- Mimir/Repositories/ItemSlotRepository.cs
- Resolve #152.
- Introduce `ItemSlotRepository`.
- Register `ItemSlotRepository` to services.
- Introduce `ItemSlotType` to handle `ItemSlotState`.
- Add `itemSlots` field to `avatar` GraphQL query.
> feat: make "itemSlots" GraphQL query

- Mimir/GraphQL/Resolvers/AvatarResolver.cs
- Mimir/GraphQL/Types/AvatarType.cs
- Mimir/GraphQL/Types/ItemSlotStateType.cs
- Mimir/GraphQL/Types/RuneSlotType.cs
- Mimir/GraphQL/Types/RuneType.cs
- Mimir/Repositories/ItemSlotRepository.cs
- Mimir/Repositories/RuneSlotRepository.cs
- Resolve #169.
- Rename `ItemSlotType` to `ItemSlotStateType`.
- Introduce `RuneSlotRepository`.
- Introduce `RuneSlotType`.
- Resolve rune slots from `AvatarResolver`.
- Add `runeSlots` field to `avatar` GraphQL query.
> feat: make "runeSlots" GraphQL query

- Lib9c.GraphQL/Types/StatMapType.cs
- Mimir/GraphQL/Resolvers/AgentResolver.cs
- Mimir/GraphQL/Types/AgentType.cs
- Mimir/GraphQL/Types/ContractType.cs
- Mimir/GraphQL/Types/ItemSlotStateType.cs
- Mimir/GraphQL/Types/RuneSlotType.cs
- Mimir/GraphQL/Types/StakeStateType.cs
- Mimir/Program.cs
- Mimir/Repositories/StakeRepository.cs
- Resolve #153.
- Introduce `StakeRepository`.
- Register repositories to services.
- Introduce `ContractType` and `StakeStateType`.
- Resolve `StakeStateV2` in `AgentResolver`.
- Add "stake" field to "agent" GraphQL query.
> feat: make `stake` GraphQL query

- Mimir.Worker/Exceptions/InvalidTypeOfActionPlainValueInternal.cs
- Mimir.Worker/Handler/BaseActionHandler.cs
- Mimir.Worker/Handler/PatchTableHandler.cs
- Mimir.Worker/Handler/ProductsHandler.cs
- Mimir.Worker/Handler/RaidActionHandler.cs
- Mimir.Worker/Poller/BlockPoller.cs
- Mimir.Worker/Program.cs
- Introduce `InvalidTypeOfActionPlainValueInternalException`.
- Fix arguments of `BaseActionHandler.TryHandleAction()` method.
- Consider when `Config.SentryDsn` is null or empty.
> fix: consider when `IAction` is not `GameAction` in  `BlockPoller` and `BaseActionHandler`

- Mimir/Arena/AvatarStatesForArena.cs
- Mimir/Controllers/ArenaController.cs
- Mimir/GraphQL/Resolvers/ArenaResolver.cs
- Mimir/GraphQL/Types/ArenaType.cs
- Mimir/Repositories/ArenaRankingRespository.cs
- Mimir/Repositories/TableSheetsRepository.cs
- Relates with #97.
- Refactor `ArenaRankingRepository`
- Add `ranking` and `leaderboard` fields to `arena` GraphQL query.
- Improve `TableSheetsRepository`.
```graphql
query arenaRank {
arena(planetName: ODIN) {
ranking(avatarAddress: "DEEaF9d47575FD29F72Aa50E36f59A213447e959")
}
}
```
```json
{
"data": {
"arena": {
"ranking": 758
}
}
}
```
I'm trying to use a feature that already exists, but it's timing out. In this PR, I ignore it and move on.
```graphql
query arenaLeaderboards {
arena(planetName: ODIN) {
leaderboard(ranking: 1, length: 10) {
score
}
}
}
```
```json
{
"errors": [
{
"message": "The request exceeded the configured timeout of `00:00:30`.",
"extensions": {
"code": "HC0045"
}
}
]
}
```
> feat: make more sub fields in the "arena" GraphQL query

- Mimir.Worker/Constants/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/BalanceHandler.cs
- Mimir.Worker/Models/State/BalanceState.cs
This pull request:
- Generalize balance handler. Now, it can register balance handler with only `Currency`. (`RegisterBalanceHandler(Currency)`).
- Now worker stores several balances in `balances` collection.
- OdinNCGCurrency
- Crystal
- StakeRune
- DailyRewardRune
- Garage
- Mead
- FreyaBlessingRune
- FreyaLiberationRune
- OdinWeaknessRune
- OdinWisdomRune
I run `Mimir.Worker` in my local environment, it seems to work.
> Handle several currency balances

- Mimir/Controllers/AgentController.cs
- Mimir/Controllers/AvatarController.cs
- Mimir/Controllers/BalanceController.cs
- Mimir/Controllers/TableSheetsController.cs
- Mimir/Enums/SheetFormat.cs
This pull request replaces `"application/json"` and `"text/csv"` with [`MediaTypeNames`](https://learn.microsoft.com/en-us/dotnet/api/system.net.mime.mediatypenames?view=net-8.0)' fields.
> Replace content type constants with pre-defiend constants

- Mimir.Models/AdventureBoss/SeasonInfo.cs
- Mimir.Worker.Tests/Handler/AdventureBoss/SeasonInfoHandlerTests.cs
- Mimir.Worker/Handler/AdventureBoss/SeasonInfoHandler.cs
- Mimir.Worker/Models/State/AdventureBoss/SeasonInfoState.cs
- Mimir/GraphQL/Objects/AdventureBossObject.cs
- Mimir/GraphQL/Resolvers/AdventureBossResolver.cs
- Mimir/GraphQL/Types/AdventureBoss/SeasonInfoType.cs
- Mimir/GraphQL/Types/AdventureBossType.cs
- Mimir/GraphQL/Types/QueryType.cs
- Mimir/Program.cs
- Mimir/Repositories/AdventureBoss/SeasonInfoRepository.cs
- Relates with #222.
- Introduce `Mimir.Models.AdventureBoss.SeasonInfo`.
- Fix type of `SeasonInfoState.Object`.
- Introduce `SeaonInfoRepository`.
- Introduce `SeasonInfoType`.
- Introduce `AdventureBossType` with resolver.
- Add `adventureBoss` GraphQL query.
```graphql
query adventureBossSeasonInfo {
adventureBoss {
season {
address
bossId
endBlockIndex
nextStartBlockIndex
season
startBlockIndex
}
}
}
```
```json
{
"data": {
"adventureBoss": {
"season": {
"address": "0x0000000000000000000000000000000000000000",
"bossId": 666,
"endBlockIndex": 10000,
"nextStartBlockIndex": 19999,
"season": 1,
"startBlockIndex": 9999
}
}
}
}
```
> feat: Introduce "adventureBoss" GraphQL query

- Mimir/GraphQL/Resolvers/AdventureBossResolver.cs
- Mimir/GraphQL/Types/AdventureBossType.cs
- Mimir/Repositories/AdventureBoss/SeasonInfoRepository.cs
- Relates with #222.
```graphql
query adventureBossSeasonInfo {
adventureBoss {
season(number: 0) {
address
bossId
endBlockIndex
nextStartBlockIndex
season
startBlockIndex
}
}
}
```
```json
{
"data": {
"adventureBoss": {
"season": {
"address": "0x0000000000000000000000000000000000000000",
"bossId": 666,
"endBlockIndex": 10000,
"nextStartBlockIndex": 19999,
"season": 1,
"startBlockIndex": 9999
}
}
}
}
```
> feat: apply season number to `adventureBoss > season` GraphQL query

- Lib9c.Models/Mails/Mail.cs
- Lib9c.Models/States/AgentState.cs
- Lib9c.Models/States/AvatarState.cs
- Mimir.MongoDB/Bson/AvatarDocument.cs
- Mimir.MongoDB/Bson/Serialization/SerializationRegistry.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Libplanet/AddressSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Libplanet/CurrencySerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Libplanet/FungibleAssetValueSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/LibplanetCryptoAddressBsonSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/System/BigIntegerSerializer.cs
- Mimir.Worker/Handler/AvatarStateHandler.cs
- Mimir.Worker/Services/MongoDbService.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/GraphQL/Types/QueryType.cs
- Mimir/Repositories/AgentRepository.cs
- Mimir/Repositories/AvatarRepository.cs
- Mimir/Services/MongoDbService.cs
- Integrate `AvatarDocument` MongoDB model with GraphQL schema.
- Introduce `SerializationRegistry`.
- Introduce and register several BsonSerializers.
- Apply several attribute to for Bson deserialization and GraphQL schema generation.
- Add `AvatarRepository.GetByAddressAsync`.
- Move "avatar" GraphQL query.
> Integrate `AvatarDocument` MongoDB model with GraphQL schema

- Mimir.Worker/ActionHandler/ProductsHandler.cs
- Mimir.Worker/Exceptions/StateIsNullException.cs
- Mimir.Worker/Util/StateGetter.cs
Sometimes the product exists, but its state is `Bencodex.Types.Null`
I think this is an abnormal situation, likely caused by an error or remnants of past data.
Nevertheless, we should handle it appropriately.
> Handle bencodex null product

- Lib9c.GraphQL/Enums/CurrencyMethodType.cs
- Lib9c.GraphQL/Extensions/CurrencyInputExtensions.cs
- Lib9c.GraphQL/Extensions/CurrencyTickerStringExtensions.cs
- Lib9c.GraphQL/InputObjectTypes/CurrencyInputType.cs
- Lib9c.GraphQL/InputObjects/CurrencyInput.cs
- Lib9c.GraphQL/Types/CurrencyType.cs
- Mimir.MongoDB/Bson/BalanceDocument.cs
- Mimir.Worker/Handler/BalanceHandler.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- Mimir/Repositories/BalanceRepository.cs
- Add `CurrencyType`, `CurrencyInputType` for GraphQL.
- Add `CurrencyTickerStringExtensions`.
- Add `BalanceRepository`
- Change type of `BalanceDocument.Object` from `FungibleAssetValue` to `string`.
- Add "balance" GraphQL query.
> feat: add "balance" GraphQL query

- Lib9c.Models/States/WorldBossKillRewardRecord.cs
- Lib9c.Models/States/WorldBossState.cs
- Lib9c.Models/States/WorldInformationState.cs
- Lib9c.Models/WorldInformation/World.cs
- Mimir.MongoDB/Bson/WorldInformationDocument.cs
- Mimir.MongoDB/CollectionNames.cs
- Mimir.Worker/Handler/AddressHandlerMappings.cs
- Mimir.Worker/Handler/AllRuneStateHandler.cs
- Mimir.Worker/Handler/WorldInformationStateHandler.cs
- Mimir.Worker/Poller/TxPoller.cs
Related to https://github.com/planetarium/mimir/issues/323
> Reactivate world information

- Mimir.MongoDB/Bson/ArenaDocument.cs
- Mimir.MongoDB/Bson/Simplified/SimplifiedAvatarState.cs
- Mimir.Worker/ActionHandler/BattleArenaHandler.cs
- Mimir.Worker/ActionHandler/JoinArenaHandler.cs
- Mimir.Worker/CollectionUpdaters/ArenaCollectionUpdater.cs
- Mimir.Worker/Initializer/ArenaInitializer.cs
- Mimir/Repositories/ArenaRepository.cs
> Store `SimpleAvatar` in `ArenaDocument`

- Mimir.Worker/ActionHandler/CombinationSlotStateHandler.cs
- Mimir.Worker/ActionHandler/PetStateHandler.cs
- Mimir.Worker/ActionHandler/RapidCombinationHandler.cs
- Mimir.Worker/Poller/TxPoller.cs
- Handle `RapidCombination` action separatly.
- Handle `PetState` in `RapidCombinationHandler`.
- Register `RapidCombinationHandler` to `TxPoller`.
> fix: handler for `RapidCombination` action

- Lib9c.Models/States/RaiderState.cs
- Lib9c.Models/States/WorldBossKillRewardRecord.cs
- Lib9c.Models/States/WorldBossState.cs
- Mimir.Worker/ActionHandler/BaseActionHandler.cs
- Mimir.Worker/ActionHandler/CombinationSlotStateHandler.cs
- Mimir.Worker/ActionHandler/PatchTableHandler.cs
- Mimir.Worker/ActionHandler/PetStateHandler.cs
- Mimir.Worker/ActionHandler/ProductsHandler.cs
- Mimir.Worker/ActionHandler/RaidHandler.cs
- Mimir.Worker/ActionHandler/RapidCombinationHandler.cs
- Mimir.Worker/Util/StateGetter.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- Mimir/Repositories/WorldBossKillRewardRecordRepository.cs
- Mimir/Repositories/WorldBossRaiderRepository.cs
- Mimir/Repositories/WorldBossRepository.cs
worldBoss: Retrieve a list of product ids that a specific avatar has listed in the market.
worldBossRaider: Look up a product by product Id.
worldBossKillRewardRecord: Retrieve all products in the marketplace.
```graphql
query {
worldBoss {
id
level
startedBlockIndex
endedBlockIndex
}
worldBossRaider(avatarAddress: "6ab1bBD3b293BB4239e078F6ECEf8653FCE08268") {
avatarAddress
avatarName
claimedBlockIndex
cp
highScore
}
worldBossKillRewardRecord(
avatarAddress: "6ab1bBD3b293BB4239e078F6ECEf8653FCE08268"
) {
rewardRecordDictionary {
key
value
}
}
}
```
```json
{
"data": {
"worldBoss": {
"id": 0,
"level": 299,
"startedBlockIndex": 11736101,
"endedBlockIndex": 11887300
},
"worldBossRaider": {
"avatarAddress": "0x6ab1bBD3b293BB4239e078F6ECEf8653FCE08268",
"avatarName": "LuongThienDi", …
```
> feat: introduce GraphQL queries for world boss

- Lib9c.Models/States/AllRuneState.cs
- Mimir.MongoDB/CollectionNames.cs
- Mimir.MongoDB/Repositories/AllRuneRepository.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
- Sort some methods and lines in alphabetical order.
- Fix "allCombinationSlotStates" to "combinationSlotStates"
- Code clean up of `CollectionNames`
- Register `AllRuneDocument` type to `CollectionNames`
- Add `init` keyword to `AllRuneState.Runes` property
- Fix `AllRuneRepository` and register to program services
- Add "runes" graphQL query
```graphql
query {
runes(avatarAddress: "Ae441376eb509Aad4eE57cefca1fB79FB5e34251") {
level
runeId
}
}
```
```json
{
"data": {
"runes": [
{
"level": 1,
"runeId": 10001
},
{
"level": 26,
"runeId": 30001
}
]
}
}
```
> feat: add "runes" graphQL query

- Mimir.Worker/Services/MongoDbService.cs
It resolves #408.
Since #403, `PlanetType` becomes enum type. And its `ToString` behavior has changed so such situation was occurred. This pull request forces using lowercase database name.
Previous implementation:
https://github.com/planetarium/mimir/blob/3b64444708acf2eb6a2c0caca8d322f329b30d90/Mimir.Worker/Constants/PlanetType.cs#L27-L29
Current implementation:
See https://learn.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=net-8.0
> Force lowercase database name

- Mimir.MongoDB/CollectionNames.cs
- Mimir.MongoDB/Repositories/CollectionRepository.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
This pull request resolve #405.
- Register "collection" to collection name.
- Register `CollectionRepository` to services as singleton.
- Add GraphQL query `collection`.
> feat: introduce GraphQL query for "collection"

- Lib9c.GraphQL/Types/Items/InventoryItemType.cs
- Mimir.MongoDB/Repositories/InventoryRepository.cs
- Mimir/GraphQL/Queries/Query.cs
- Mimir/Program.cs
This pull request resolve #406.
- Register `InventoryRepository` to services.
- Introduce `InventoryItemType` for GraphQL.
- Introduce GraphQL query "inventory".
> feat: introduce GraphQL query for "inventory"

- Mimir/GraphQL/Queries/Query.cs
Closes #413 
Corrected the typo in the param name comment of Query.GetPetAsync(avatarAddress, repo) method.
> [FIX]:Fixed the typo in comment

- Mimir.E2ETests/MimirGQL/query.graphql
- Mimir.E2ETests/StackTests.cs
resolve #446 
특정 address에 대해 Mimir와 Headless 서비스에서 각각 조회한 Stake의 StartedBlockIndex가 같은지 비교하는 테스트 코드를 작성합니다
**Additional FIXME**
- #448
- #449
> [MIMIR_ISSUE446] Implement e2e tests for the stake state

- Lib9c.Models/Market/FavProduct.cs
- Lib9c.Models/Market/ItemProduct.cs
- Lib9c.Models/Market/Product.cs
- Mimir.MongoDB/Bson/Extensions/BsonValueExtensions.cs
- Mimir.MongoDB/Bson/Serialization/SerializationRegistry.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/AttachmentActionResults/ItemEnhancement11ResultSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/AttachmentActionResults/ItemEnhancement12ResultSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/AttachmentActionResults/ItemEnhancement13ResultSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/AttachmentActionResults/ItemEnhancement9ResultSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/ConsumableSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/CostumeSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/EquipmentSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/ItemBaseSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/ItemUsableSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/MaterialSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/TradableMaterialSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Market/FavProductSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Market/ItemProductSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Market/ProductSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Sheets/SkillSheetRowSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Skills/SkillSerializer.cs
- Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Stats/DecimalStatSerializer.cs
- Mimir.MongoDB/Repositories/ProductRepository.cs
- Resolve #454, #456
- See also https://github.com/planetarium/mimir/issues/402#issuecomment-2438247127
```graphql
query {
product(productId: "f0994e0c-0295-493d-a395-951ca7152954") {
... on ItemProduct {
tradableItem {
id
itemType
itemSubType
elementalType
}
}
}
}
```
```json
{
"data": {
"product": {
"tradableItem": {
"id": 900109,
"itemType": "CONSUMABLE",
"itemSubType": "FOOD",
"elementalType": "NORMAL"
}
}
}
}
```
```graphql
query {
product(productId: "adc9b9c8-ea71-4a56-9549-691f631a0b23") {
... on ItemProduct {
tradableItem {
id
itemType
itemSubType
elementalType
}
}
}
}
```
```json
{
"data": {
"product": {
"tradableItem": {
"id": 10354002,
"itemType": "EQUIPMENT",
"itemSubType": "BELT",
"elementalType": "WIND"
}
}
}
}
```
> fix: handling serialized enum date in MongoDB effectively and more

- Mimir.Worker/Client/HeadlessGQLClient.cs
- Mimir.Worker/Client/Models.cs
This pull request fixes the logic to fetch transactions. To do it, I made some changes:
- Validate `GetTransactionsResponse` manually. It validates responses like below:
```json
{
"data": {
"transaction": null
},
...
}
```
```json
{
"data": {
"transaction": {
"ncTransactions": null
}
},
...
}
```
```json
{
"data": {
"transaction": {
"ncTransactions": [
{
...,
"actions": [
null
],
...
}
]
}
},
...
}
```
- Checks `"errors"` field is not `null` because there will be `errors` field when there were any errors while resolving the query, according to the GraphQL spec, https://spec.graphql.org/October2021/#sec-Errors.
- Expire cached value after 30 seconds from writing. Though it tried to validate the responses, it can cache invalid response unfortunately. So it expire the cached value after 30 …
> fix: correct the logic to fetch transactions

- Mimir.E2ETests/AgentTests.cs
add the remaining field comparisons to tests that compare only one existing field.
> add all field value comparisons to existing agent tests

- Mimir.Worker/Handler/BaseDiffHandler.cs
- Mimir.Worker/StateDocumentConverter/AddressStatePair.cs
I added a missing `continue` statement to skip the request to `headless` when the indexes are the same.
> Sleep and continue when same target and base index

- Mimir.Tests/QueryTests/ActionPointTests.cs
- Mimir.Tests/QueryTests/AgentTest.cs
- Mimir.Tests/QueryTests/AvatarQueryTest.cs
- Mimir.Tests/QueryTests/CombinationSlotsTest.cs
- Mimir.Tests/QueryTests/DailyRewardQueryTest.cs
- Mimir.Tests/TestServices.cs
Now we can make the ServiceProvider object like below.
```cs
var serviceProvider = TestServices.Builder
.With(actionPointMock.Object)
.Build();
```
> refactor: `TestServices` of `Mimir.Tests`

- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models/Lib9c.Models.csproj
- Lib9c.Models/Stats/DecimalStat.cs
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Tests/QueryTests/ActionPointTests.cs
- Mimir.Tests/QueryTests/AgentTest.cs
- Mimir.Tests/QueryTests/AvatarQueryTest.cs
- Mimir.Tests/QueryTests/CombinationSlotsTest.cs
- Mimir.Tests/QueryTests/DailyRewardQueryTest.cs
- Mimir.Tests/TestServices.cs
- Mimir/GraphQL/HttpResponseFormatter.cs
- Mimir/Mimir.csproj
resolves #498 
- Hot Chocolate: Updated to version 14.1.0
- MongoDB Libraries: Upgraded to version 3.0.0
- Removed MongoDB.Driver.GridFS as GridFS support is now included in MongoDB.Driver v3.0.0
- Code Refactor: Adjusted implementations to align with breaking changes and new features introduced in Hot Chocolate 14.1.0.
> update hot-chocolate to v14

- CONTRIBUTING.md
- Directory.Build.props
- Lib9c.GraphQL/Lib9c.GraphQL.csproj
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Lib9c.Models.csproj
- Mimir.MongoDB/Mimir.MongoDB.csproj
- Mimir.Worker/Mimir.Worker.csproj
- Mimir/Mimir.csproj
This pull request does:
- Make `Libplanet`-related dependencies depend on `LibplanetVersion` property defined in `Directory.Build.props`
- Make `Lib9c`-related dependencies depend on `Lib9cVersion` property defined in `Directory.Build.props`
- Guide to update properties in `Directory.Build.props` when bumping dependencies.
> chore: make easy to bump dependencies

- Directory.Build.props
- Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
- Lib9c.Models/Factories/MailFactory.cs
- Lib9c.Models/Mails/PatrolRewardMail.cs
- Mimir.Worker/Mimir.Worker.csproj
- bump lib9c v200270
- implement patrol reward mail
> Implement patrol reward mail
